# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsMarketingIdentifies
        - from: inputs/rsMarketingTracks
        - from: inputs/rsMarketingPages
        #- from: inputs/rsMarketingProductViewed
        #- from: inputs/rsMarketingAddedToCart
  - name: user_profile
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      vars:
        - entity_var:
            name: website_first_seen
            select: min(timestamp::date)
            from: inputs/rsMarketingTracks
        - entity_var:
            name: website_last_seen
            select: max(timestamp::date)
            from: inputs/rsMarketingTracks
        - entity_var:
            name: website_user_lifespan
            select: website_last_seen - website_first_seen
            description: Life Time Value of a customer
            dependencies:
              - website_last_seen
              - website_first_seen
        - entity_var:
            name: website_days_active
            select: count(distinct timestamp::date)
            from: inputs/rsMarketingTracks
            description: No. of days a customer was active
        - entity_var:
            name: website_products_viewed
            select: count(product_name)
            from: inputs/rsMarketingProductViewed
            where: timestamp >= '2024-01-01'
        - entity_var:
            name: website_products_added_to_cart
            select: count(product_name)
            from: inputs/rsMarketingAddedToCart
            where: timestamp >= '2024-01-01' 
        - entity_var:
            name: website_days_since_last_activity
            select: any_value(datediff(day, website_last_seen, current_timestamp))
            dependencies:
              - website_last_seen

      features:
        - website_user_lifespan
        - website_days_active
        - website_products_viewed
        - website_products_added_to_cart
        - website_days_since_last_activity
